
version: '3.8'

networks:
  url_shortener_net:
    driver: bridge
services:
  app:
    container_name: url_shortener_api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - url_shortener_net
    environment:
      - DB_HOST=d${DB_HOST}
      - DB_TYPE=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}

  db:
    container_name: database_postgres
    image: postgres:15-alpine
    networks:
      - url_shortener_net
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: